/**
 * tSIM eSIM catalogue (mock — drives the importer until the live tSIM API arrives).
 *
 * `esimId` mirrors the tSIM product code so these records map onto the provider
 * catalogue during real integration. `priceUsd` is treated as the wholesale
 * COST (`Plan.costUsd`) when imported; selling prices are computed by the
 * pricing engine in Phase 4D.
 */
export type MockPlan = {
  esimId: string
  name: string
  region: 'Asia' | 'Europe' | 'Americas' | 'Middle East' | 'Africa' | 'Oceania' | 'Global'
  destinations: string[]
  data: string
  fup: string
  days: number
  priceUsd: number
  apn: string
  country: string
  flag: string
  network: string
  speed: string
  popular: boolean
  badge?: string
}

export const plans: MockPlan[] = [
  /* ─── Asia ──────────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-JP-5GB-30D',
    name: 'Japan 5GB',
    region: 'Asia',
    destinations: ['Japan'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 9.99,
    apn: 'tsim',
    country: 'Japan',
    flag: '🇯🇵',
    network: 'NTT Docomo',
    speed: '4G/LTE',
    popular: true,
    badge: 'Popular',
  },
  {
    esimId: 'TS-JP-15GB-30D',
    name: 'Japan 15GB',
    region: 'Asia',
    destinations: ['Japan'],
    data: '15GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 17.99,
    apn: 'tsim',
    country: 'Japan',
    flag: '🇯🇵',
    network: 'SoftBank',
    speed: '5G',
    popular: false,
    badge: '5G',
  },
  {
    esimId: 'TS-KR-5GB-30D',
    name: 'South Korea 5GB',
    region: 'Asia',
    destinations: ['South Korea'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 9.99,
    apn: 'tsim',
    country: 'South Korea',
    flag: '🇰🇷',
    network: 'SK Telecom',
    speed: '5G',
    popular: true,
    badge: '5G',
  },
  {
    esimId: 'TS-TH-5GB-30D',
    name: 'Thailand 5GB',
    region: 'Asia',
    destinations: ['Thailand'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 6.99,
    apn: 'tsim',
    country: 'Thailand',
    flag: '🇹🇭',
    network: 'AIS',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-IN-3GB-28D',
    name: 'India 3GB',
    region: 'Asia',
    destinations: ['India'],
    data: '3GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 28,
    priceUsd: 3.99,
    apn: 'tsim',
    country: 'India',
    flag: '🇮🇳',
    network: 'Airtel',
    speed: '4G/LTE',
    popular: false,
    badge: 'Budget',
  },
  {
    esimId: 'TS-IN-10GB-28D',
    name: 'India 10GB',
    region: 'Asia',
    destinations: ['India'],
    data: '10GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 28,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'India',
    flag: '🇮🇳',
    network: 'Jio',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-SG-3GB-30D',
    name: 'Singapore 3GB',
    region: 'Asia',
    destinations: ['Singapore'],
    data: '3GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 6.99,
    apn: 'tsim',
    country: 'Singapore',
    flag: '🇸🇬',
    network: 'Singtel',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-MY-5GB-30D',
    name: 'Malaysia 5GB',
    region: 'Asia',
    destinations: ['Malaysia'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 5.99,
    apn: 'tsim',
    country: 'Malaysia',
    flag: '🇲🇾',
    network: 'Maxis',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-ID-5GB-30D',
    name: 'Indonesia 5GB',
    region: 'Asia',
    destinations: ['Indonesia'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 5.99,
    apn: 'tsim',
    country: 'Indonesia',
    flag: '🇮🇩',
    network: 'Telkomsel',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-VN-5GB-30D',
    name: 'Vietnam 5GB',
    region: 'Asia',
    destinations: ['Vietnam'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 5.99,
    apn: 'tsim',
    country: 'Vietnam',
    flag: '🇻🇳',
    network: 'Viettel',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-PH-5GB-30D',
    name: 'Philippines 5GB',
    region: 'Asia',
    destinations: ['Philippines'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 5.99,
    apn: 'tsim',
    country: 'Philippines',
    flag: '🇵🇭',
    network: 'Globe',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-ASIA-10GB-30D',
    name: 'Asia Regional 10GB',
    region: 'Asia',
    destinations: ['Japan', 'South Korea', 'Thailand', 'Singapore', 'Malaysia', 'Indonesia', 'Vietnam', 'Philippines', 'Hong Kong', 'Taiwan'],
    data: '10GB',
    fup: 'Full 4G/LTE speed across 13 Asian destinations',
    days: 30,
    priceUsd: 18.99,
    apn: 'tsim.global',
    country: 'Asia',
    flag: '🌏',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: true,
    badge: 'Regional',
  },

  /* ─── Europe ────────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-EU-10GB-30D',
    name: 'Europe Regional 10GB',
    region: 'Europe',
    destinations: ['United Kingdom', 'France', 'Germany', 'Italy', 'Spain', 'Netherlands', 'Portugal', 'Greece', 'Austria', 'Switzerland'],
    data: '10GB',
    fup: 'Full 4G/LTE speed across 36 European destinations',
    days: 30,
    priceUsd: 12.99,
    apn: 'tsim.global',
    country: 'Europe',
    flag: '🇪🇺',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: true,
    badge: 'Best Value',
  },
  {
    esimId: 'TS-EU-20GB-30D',
    name: 'Europe Regional 20GB',
    region: 'Europe',
    destinations: ['United Kingdom', 'France', 'Germany', 'Italy', 'Spain', 'Netherlands', 'Portugal', 'Greece', 'Austria', 'Switzerland'],
    data: '20GB',
    fup: 'Full 4G/LTE speed across 36 European destinations',
    days: 30,
    priceUsd: 19.99,
    apn: 'tsim.global',
    country: 'Europe',
    flag: '🇪🇺',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-GB-5GB-30D',
    name: 'United Kingdom 5GB',
    region: 'Europe',
    destinations: ['United Kingdom'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'UK',
    flag: '🇬🇧',
    network: 'EE',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-FR-5GB-30D',
    name: 'France 5GB',
    region: 'Europe',
    destinations: ['France'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'France',
    flag: '🇫🇷',
    network: 'Orange',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-DE-5GB-30D',
    name: 'Germany 5GB',
    region: 'Europe',
    destinations: ['Germany'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'Germany',
    flag: '🇩🇪',
    network: 'Deutsche Telekom',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-IT-5GB-30D',
    name: 'Italy 5GB',
    region: 'Europe',
    destinations: ['Italy'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'Italy',
    flag: '🇮🇹',
    network: 'TIM',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-ES-5GB-30D',
    name: 'Spain 5GB',
    region: 'Europe',
    destinations: ['Spain'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'Spain',
    flag: '🇪🇸',
    network: 'Movistar',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-TR-7GB-30D',
    name: 'Turkey 7GB',
    region: 'Europe',
    destinations: ['Turkey'],
    data: '7GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 6.99,
    apn: 'tsim',
    country: 'Turkey',
    flag: '🇹🇷',
    network: 'Turkcell',
    speed: '4G/LTE',
    popular: false,
  },

  /* ─── Americas ──────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-US-5GB-30D',
    name: 'USA 5GB',
    region: 'Americas',
    destinations: ['United States'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 8.99,
    apn: 'tsim',
    country: 'USA',
    flag: '🇺🇸',
    network: 'T-Mobile',
    speed: '5G',
    popular: true,
    badge: '5G',
  },
  {
    esimId: 'TS-US-15GB-30D',
    name: 'USA 15GB',
    region: 'Americas',
    destinations: ['United States'],
    data: '15GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 16.99,
    apn: 'tsim',
    country: 'USA',
    flag: '🇺🇸',
    network: 'AT&T',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-CA-5GB-30D',
    name: 'Canada 5GB',
    region: 'Americas',
    destinations: ['Canada'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 8.99,
    apn: 'tsim',
    country: 'Canada',
    flag: '🇨🇦',
    network: 'Rogers',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-MX-5GB-30D',
    name: 'Mexico 5GB',
    region: 'Americas',
    destinations: ['Mexico'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.99,
    apn: 'tsim',
    country: 'Mexico',
    flag: '🇲🇽',
    network: 'Telcel',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-BR-5GB-30D',
    name: 'Brazil 5GB',
    region: 'Americas',
    destinations: ['Brazil'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 8.49,
    apn: 'tsim',
    country: 'Brazil',
    flag: '🇧🇷',
    network: 'Vivo',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-AM-10GB-30D',
    name: 'Americas Regional 10GB',
    region: 'Americas',
    destinations: ['United States', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'Chile', 'Colombia', 'Peru'],
    data: '10GB',
    fup: 'Full 4G/LTE speed across 15 destinations in the Americas',
    days: 30,
    priceUsd: 21.99,
    apn: 'tsim.global',
    country: 'Americas',
    flag: '🌎',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: false,
    badge: 'Regional',
  },

  /* ─── Middle East ───────────────────────────────────────────────────────── */
  {
    esimId: 'TS-AE-5GB-30D',
    name: 'UAE 5GB',
    region: 'Middle East',
    destinations: ['United Arab Emirates'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 8.99,
    apn: 'tsim',
    country: 'UAE',
    flag: '🇦🇪',
    network: 'Etisalat',
    speed: '5G',
    popular: true,
  },
  {
    esimId: 'TS-SA-5GB-30D',
    name: 'Saudi Arabia 5GB',
    region: 'Middle East',
    destinations: ['Saudi Arabia'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 9.49,
    apn: 'tsim',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    network: 'STC',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-IL-5GB-30D',
    name: 'Israel 5GB',
    region: 'Middle East',
    destinations: ['Israel'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 9.99,
    apn: 'tsim',
    country: 'Israel',
    flag: '🇮🇱',
    network: 'Partner',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-QA-5GB-30D',
    name: 'Qatar 5GB',
    region: 'Middle East',
    destinations: ['Qatar'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 9.49,
    apn: 'tsim',
    country: 'Qatar',
    flag: '🇶🇦',
    network: 'Ooredoo',
    speed: '5G',
    popular: false,
  },

  /* ─── Africa ────────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-EG-5GB-30D',
    name: 'Egypt 5GB',
    region: 'Africa',
    destinations: ['Egypt'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 6.99,
    apn: 'tsim',
    country: 'Egypt',
    flag: '🇪🇬',
    network: 'Vodafone EG',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-ZA-5GB-30D',
    name: 'South Africa 5GB',
    region: 'Africa',
    destinations: ['South Africa'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.49,
    apn: 'tsim',
    country: 'South Africa',
    flag: '🇿🇦',
    network: 'Vodacom',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-MA-5GB-30D',
    name: 'Morocco 5GB',
    region: 'Africa',
    destinations: ['Morocco'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 7.49,
    apn: 'tsim',
    country: 'Morocco',
    flag: '🇲🇦',
    network: 'Maroc Telecom',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-KE-3GB-30D',
    name: 'Kenya 3GB',
    region: 'Africa',
    destinations: ['Kenya'],
    data: '3GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 6.49,
    apn: 'tsim',
    country: 'Kenya',
    flag: '🇰🇪',
    network: 'Safaricom',
    speed: '4G/LTE',
    popular: false,
    badge: 'Budget',
  },

  /* ─── Oceania ───────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-AU-5GB-30D',
    name: 'Australia 5GB',
    region: 'Oceania',
    destinations: ['Australia'],
    data: '5GB',
    fup: 'Full 5G speed; no throttling within allowance',
    days: 30,
    priceUsd: 8.99,
    apn: 'tsim',
    country: 'Australia',
    flag: '🇦🇺',
    network: 'Telstra',
    speed: '5G',
    popular: false,
  },
  {
    esimId: 'TS-NZ-5GB-30D',
    name: 'New Zealand 5GB',
    region: 'Oceania',
    destinations: ['New Zealand'],
    data: '5GB',
    fup: 'Full 4G/LTE speed until data is used up',
    days: 30,
    priceUsd: 8.99,
    apn: 'tsim',
    country: 'New Zealand',
    flag: '🇳🇿',
    network: 'Spark',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-OC-8GB-30D',
    name: 'Oceania Regional 8GB',
    region: 'Oceania',
    destinations: ['Australia', 'New Zealand', 'Fiji'],
    data: '8GB',
    fup: 'Full 4G/LTE speed across Australia, New Zealand & Fiji',
    days: 30,
    priceUsd: 16.99,
    apn: 'tsim.global',
    country: 'Oceania',
    flag: '🌏',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: false,
    badge: 'Regional',
  },

  /* ─── Global ────────────────────────────────────────────────────────────── */
  {
    esimId: 'TS-GL-1GB-30D',
    name: 'Global 1GB',
    region: 'Global',
    destinations: ['United States', 'United Kingdom', 'Japan', 'Australia', 'France', 'Germany', 'India', 'UAE', 'Singapore', 'Thailand', '+120 more'],
    data: '1GB',
    fup: 'Full 4G/LTE speed across 130+ destinations',
    days: 30,
    priceUsd: 15.99,
    apn: 'tsim.global',
    country: 'Global',
    flag: '🌍',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: false,
  },
  {
    esimId: 'TS-GL-5GB-30D',
    name: 'Global 5GB',
    region: 'Global',
    destinations: ['United States', 'United Kingdom', 'Japan', 'Australia', 'France', 'Germany', 'India', 'UAE', 'Singapore', 'Thailand', '+120 more'],
    data: '5GB',
    fup: 'Full 4G/LTE speed across 130+ destinations',
    days: 30,
    priceUsd: 29.99,
    apn: 'tsim.global',
    country: 'Global',
    flag: '🌍',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: true,
    badge: 'Popular',
  },
  {
    esimId: 'TS-GL-10GB-30D',
    name: 'Global 10GB',
    region: 'Global',
    destinations: ['United States', 'United Kingdom', 'Japan', 'Australia', 'France', 'Germany', 'India', 'UAE', 'Singapore', 'Thailand', '+120 more'],
    data: '10GB',
    fup: 'Full 4G/LTE speed across 130+ destinations',
    days: 30,
    priceUsd: 49.99,
    apn: 'tsim.global',
    country: 'Global',
    flag: '🌍',
    network: 'Multi-network',
    speed: '4G/LTE',
    popular: false,
  },
]
